version: 1

before:
  hooks:
    - go generate ./...

builds:
  - goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -ldflags -H=windowsgui

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

changelog:
  sort: asc
  filters:
    include:
      - "^feat:"
      - "^fix:"
