name: Enhancement Proposal
description: Propose an enhancement
body:
  - type: markdown
    attributes:
      value: |
        This template is for comprehensive proposals. If you want to simply suggest a feature, please [create a discussion](https://github.com/getseabird/seabird/discussions/categories/ideas).

  - type: textarea
    attributes:
      label: Summary
      description: Short explanation of the feature.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Motivation
      description:
        Why are we doing this? What use cases does it support? What is the
        expected outcome?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposal
      description: |
        Explain the proposed solution in detail. If significant UI changes are required for this feature, please include mockups.
    validations:
      required: true
